#ifndef _COLOR_HPP_
#define _COLOR_HPP_

#include<Windows.h>
#define B_INTENSITY BACKGROUND_INTENSITY
#define B_RED   BACKGROUND_RED
#define B_GREEN BACKGROUND_GREEN
#define B_BLUE  BACKGROUND_BLUE
#define B_ORANGE  BACKGROUND_RED|BACKGROUND_GREEN
#define B_CYAN    BACKGROUND_GREEN|BACKGROUND_BLUE
#define B_MAGENTA BACKGROUND_RED|BACKGROUND_BLUE
#define B_WHITE   BACKGROUND_RED|BACKGROUND_GREEN|BACKGROUND_BLUE
#define B_BLACK   0

#define F_INTENSITY FOREGROUND_INTENSITY
#define F_RED   FOREGROUND_RED
#define F_GREEN FOREGROUND_GREEN
#define F_BLUE  FOREGROUND_BLUE
#define F_ORANGE  FOREGROUND_RED|FOREGROUND_GREEN
#define F_CYAN    FOREGROUND_GREEN|FOREGROUND_BLUE
#define F_MAGENTA FOREGROUND_RED|FOREGROUND_BLUE
#define F_WHITE   FOREGROUND_RED|FOREGROUND_GREEN|FOREGROUND_BLUE
#define F_BLACK   0

void setColor(int fc = -1, int bc = -1);


#endif // !_COLOR_HPP_
